-- Insert 30 musical instrument products
INSERT INTO Products (Name, Price, Description, Category, StockQuantity, ImageUrl)
VALUES ('Fender Stratocaster Electric Guitar', 1299.99, 'Classic American-made electric guitar with iconic sound', 'Guitars', 10, 'https://example.com/stratocaster.jpg'),
       ('Yamaha P-125 Digital Piano', 649.99, 'Compact 88-key digital piano with weighted keys', 'Keyboards', 15, 'https://example.com/yamaha-piano.jpg'),
       ('Yamaha YAS-280 Alto Saxophone', 899.99, 'Student model alto saxophone with quality sound', 'Woodwinds', 8, 'https://example.com/saxophone.jpg'),
       ('Pearl Export Series Drum Kit', 749.99, 'Complete 5-piece drum set with cymbals', 'Drums', 5, 'https://example.com/pearl-drumkit.jpg'),
       ('Gibson Les Paul Standard', 2499.99, 'Legendary solid body electric guitar', 'Guitars', 6, 'https://example.com/les-paul.jpg'),
       ('Korg Kronos 2 Synthesizer', 3299.99, 'Professional workstation synthesizer', 'Keyboards', 4, 'https://example.com/korg-kronos.jpg'),
       ('Selmer Series III Trumpet', 1599.99, 'Professional B-flat trumpet', 'Brass', 7, 'https://example.com/trumpet.jpg'),
       ('Roland TD-17KVX Electronic Drum Kit', 1299.99, 'Advanced electronic drum set with mesh heads', 'Drums', 6, 'https://example.com/roland-drums.jpg'),
       ('Martin D-28 Acoustic Guitar', 3299.99, 'Legendary dreadnought acoustic guitar', 'Guitars', 4, 'https://example.com/martin-guitar.jpg'),
       ('Nord Stage 3 Compact Keyboard', 4299.99, 'Professional stage keyboard', 'Keyboards', 3, 'https://example.com/nord-keyboard.jpg'),
       ('Shure SM58 Microphone', 99.99, 'Industry-standard vocal microphone', 'Microphones', 20, 'https://example.com/sm58.jpg'),
       ('Ibanez RG550 Electric Guitar', 999.99, 'High-performance electric guitar', 'Guitars', 8, 'https://example.com/ibanez-guitar.jpg'),
       ('Akai MPK Mini MKIII MIDI Keyboard', 119.99, 'Compact MIDI controller', 'Keyboards', 25, 'https://example.com/akai-midi.jpg'),
       ('Zildjian A Custom Cymbal Set', 799.99, 'Professional cymbal set for drummers', 'Drums', 6, 'https://example.com/zildjian-cymbals.jpg'),
       ('Steinway Model B Grand Piano', 89999.99, 'Professional concert grand piano', 'Keyboards', 1, 'https://example.com/steinway.jpg'),
       ('Taylor 814ce Acoustic Guitar', 4999.99, 'Premium acoustic-electric guitar', 'Guitars', 5, 'https://example.com/taylor-guitar.jpg'),
       ('Sennheiser MD 421 Microphone', 379.99, 'Professional dynamic microphone', 'Microphones', 12, 'https://example.com/md421.jpg'),
       ('Moog Subsequent 37 Synthesizer', 1599.99, 'Analog synthesizer with rich sound', 'Keyboards', 7, 'https://example.com/moog-synth.jpg'),
       ('Ludwig Supraphonic Snare Drum', 599.99, 'Legendary metal snare drum', 'Drums', 10, 'https://example.com/ludwig-snare.jpg'),
       ('Fender Precision Bass', 1499.99, 'Iconic electric bass guitar', 'Guitars', 8, 'https://example.com/precision-bass.jpg'),
       ('Nord Electro 6D', 2999.99, 'Stage keyboard with vintage sounds', 'Keyboards', 5, 'https://example.com/nord-electro.jpg'),
       ('Selmer Reference 54 Alto Saxophone', 4999.99, 'Professional alto saxophone', 'Woodwinds', 3, 'https://example.com/selmer-saxophone.jpg'),
       ('DW Performance Series Drum Kit', 2999.99, 'Professional drum kit', 'Drums', 4, 'https://example.com/dw-drums.jpg'),
       ('AKG C414 XLII Microphone', 1099.99, 'Multi-pattern large-diaphragm condenser mic', 'Microphones', 6, 'https://example.com/akg-mic.jpg'),
       ('Rickenbacker 4001 Bass', 3499.99, 'Classic electric bass guitar', 'Guitars', 4, 'https://example.com/rickenbacker-bass.jpg'),
       ('Roland Jupiter-X Synthesizer', 1999.99, 'Modern analog modeling synthesizer', 'Keyboards', 6, 'https://example.com/roland-synth.jpg'),
       ('Vandoren V16 Tenor Saxophone', 699.99, 'Professional tenor saxophone reed', 'Woodwinds', 15, 'https://example.com/vandoren-reed.jpg'),
       ('Tama Starclassic Drum Kit', 1999.99, 'High-end drum kit', 'Drums', 5, 'https://example.com/tama-drums.jpg'),
       ('Apple Logic Pro X', 199.99, 'Professional music production software', 'Software', 50, 'https://example.com/logic-pro.jpg');